### ISSUE TITLE
Broken links in zh reference page

### ISSUE THREAD

**Issue by czy1996** [tutureproject/docs#10]
![image](https://user-images.githubusercontent.com/11272461/45481267-b0cfbf00-b77d-11e8-830b-90bd90932701.png)

The links below report a 404 error
> https://docs.tuture.co/zh/reference/cli-commands.zh-CN.html 
> https://docs.tuture.co/zh/reference/tuture-yml-spec.zh-CN.html，

whereas corresponding links on side bar work, like below

> https://docs.tuture.co/zh/reference/cli-commands.html
> https://docs.tuture.co/zh/reference/tuture-yml-spec.html

sesms a vuepress bug

**Comment by pftom** [comment]
@czy1996 Thanks for your great job! It seems we haven't deploy this doc after we fixed that problem.

**Comment by pftom** [comment]
@czy1996 Now you can visit https://docs.tuture.co/reference/cli-commands.zh-CN.html for newly docs experiences. 😀

**Comment by czy1996** [comment]
@pftom you're welcome
